server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: pms-route # \u5546\u54C1\u7BA1\u7406\u8DEF\u7531
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: oms-route # \u8BA2\u5355\u7BA1\u7406\u8DEF\u7531
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: ums-route # \u7528\u6237\u7BA1\u7406\u8DEF\u7531
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: wms-route # \u4ED3\u5E93\u7BA1\u7406\u8DEF\u7531
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: sms-route # \u8425\u9500\u7BA1\u7406\u8DEF\u7531
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: search-route
          uri: lb://search-service
          predicates:
            - Host=search.gmall.com
#        - id: search-route # \u8425\u9500\u7BA1\u7406\u8DEF\u7531
#          uri: lb://search-service
#          predicates:
#            - Path=/search/**
        - id: index-route1 # 首页的同步请求路由
          uri: lb://index-service
          predicates:
            - Host=gmall.com, www.gmall.com
          # - Path=/index/**  如果写在一个里面，他们的关系是and关系
        - id: index-route2 # 首页的异步请求路由
          uri: lb://index-service
          predicates:
            - Path=/index/**
        - id: item-route
          uri: lb://item-service
          predicates:
            - Host=item.gmall.com
        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Host=sso.gmall.com
        - id: cart-route
          uri: lb://cart-service
          predicates:
            - Host=cart.gmall.com
        - id: order-route
          uri: lb://order-service
          predicates:
            - Host=order.gmall.com
          filters:
            - Auth=/
jwt:
  pubKeyPath: E:\MyWork\project\rsa\rsa.pub
  cookieName: GMALL-TOKEN